### ISSUE TITLE
Batch Gradient Descent global optimum

### ISSUE THREAD

**Issue by wiktorstankiewicz** [Jakub-Ner/fiszki-ist#9]
Batch Gradient Descent: uaktualnianie wag po wszystkich wzorcach uczących (po całej epoce, of line training). Gwarantuje zbieżność do globalnego optimum 😃

BGD niestety w ogólności nie gwarantuje globalnego optimum:(

**Comment by Jakub-Ner** [comment]
Dzięki :)

Już poprawiłem na
- **Batch Gradient Descent**: uaktualnianie wag po wszystkich wzorcach uczących (po całej epoce, of line training), co zwiększa stabilność treningu (bo liczymy gradient dopiero po przejsciu przez cały zbiór uczący)
